add missing sys/time.h header
struct timeval is defined in sys/time.h with a musl toolchain.

Fixes:
In file included from Function.cc:16:0:
Calculator.h:241:17: error: field 't_print_end' has incomplete type 'timeval'
  struct timeval t_print_end;
                 ^~~~~~~~~~~
Calculator.h:241:9: note: forward declaration of 'struct timeval'
  struct timeval t_print_end;
         ^~~~~~~
In file included from Calculator.cc:14:0:
Calculator.h:241:17: error: field 't_print_end' has incomplete type 'timeval'
  struct timeval t_print_end;
                 ^~~~~~~~~~~
Calculator.h:241:9: note: forward declaration of 'struct timeval'
  struct timeval t_print_end;
         ^~~~~~~
In file included from DataSet.cc:17:0:
Calculator.h:241:17: error: field 't_print_end' has incomplete type 'timeval'
  struct timeval t_print_end;
                 ^~~~~~~~~~~
Calculator.h:241:9: note: forward declaration of 'struct timeval'
  struct timeval t_print_end;
         ^~~~~~~
In file included from Variable.cc:16:0:
Calculator.h:241:17: error: field 't_print_end' has incomplete type 'timeval'
  struct timeval t_print_end;
                 ^~~~~~~~~~~